# Generated by Django 5.1.1 on 2024-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
