# Generated by Django 5.1.1 on 2024-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_v2', '0002_remove_order_order_number_alter_order_stripe_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
