# Generated by Django 5.1.1 on 2024-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='distance',
            field=models.CharField(choices=[('5k', '5k'), ('10k', '10k'), ('half_marathon', 'Half Marathon'), ('marathon', 'Marathon'), ('50k', '50k'), ('80k', '80k'), ('100k', '100k'), ('160k', '160k'), ('200k', '200k')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='file',
            field=models.FileField(default='default_plans/default_plan.pdf', upload_to='plans/'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='image',
            field=models.ImageField(default='default_images/default_image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='sample_file',
            field=models.FileField(default='default_samples/default_sample.pdf', upload_to='samples/'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='terrain',
            field=models.CharField(choices=[('road', 'Road'), ('trail', 'Trail')], max_length=20),
        ),
    ]
