# Generated by Django 5.1.1 on 2024-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_trainingplan_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='elevation',
            field=models.CharField(choices=[('0-500m', '0m-500m'), ('500-1000m', '500m-1000m'), ('1000-1500m', '1000m-1500m'), ('1500-2000m', '1500m-2000m'), ('2000-2500m', '2000m-2500m'), ('2500-3000m', '2500m-3000m'), ('3000-3500m', '3000m-3500m'), ('3500-4000m', '3500m-4000m'), ('4000-4500m', '4000m-4500m'), ('4500-5000m', '4500m-5000m'), ('5000-5500m', '5000m-5500m'), ('5500-6000m', '5500m-6000m'), ('6000-6500m', '6000m-6500m'), ('6500-7000m', '6500m-7000m'), ('7000-7500m', '7000m-7500m'), ('7500-8000m', '7500m-8000m'), ('8000-8500m', '8000m-8500m'), ('8500-9000m', '8500m-9000m'), ('9000-9500m', '9000m-9500m'), ('9500-10000m', '9500m-10000m')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='image',
            field=models.ImageField(default='default_images/default_image.jpg', upload_to='images/'),
        ),
    ]
