# Generated by Django 5.1.1 on 2024-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_trainingplan_event_date_alter_trainingplan_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='terrain',
            field=models.CharField(choices=[('road', 'Road'), ('trail', 'Trail'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
