# Generated by Django 5.1.1 on 2024-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_trainingplan_terrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='file',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='sample_file',
        ),
    ]
